// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCivmrMEhWbAfqx1Ow-WIfMuAf0dft5nV0',
    appId: '1:565344287687:web:7ac0ff4614d9b3351377e2',
    messagingSenderId: '565344287687',
    projectId: 'edugestaoconvidados',
    authDomain: 'edugestaoconvidados.firebaseapp.com',
    storageBucket: 'edugestaoconvidados.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPVJkP6rlWyxmXtFrsL9fVXpwsjWAtIVM',
    appId: '1:565344287687:android:99a40afc57c1c3611377e2',
    messagingSenderId: '565344287687',
    projectId: 'edugestaoconvidados',
    storageBucket: 'edugestaoconvidados.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATQ413vs4Cj3eJZPKSAkbGCXfXL-m0yd0',
    appId: '1:565344287687:ios:aaec31e2e76ece551377e2',
    messagingSenderId: '565344287687',
    projectId: 'edugestaoconvidados',
    storageBucket: 'edugestaoconvidados.firebasestorage.app',
    iosBundleId: 'com.example.edugestaoConvidadosApp',
  );

}